name: Deploy to Koyeb

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | sh
          
      - name: Login to Koyeb
        run: |
          koyeb login --token ${{ secrets.KOYEB_TOKEN }}
          
      - name: Build and Deploy to Koyeb
        run: |
          koyeb service create eshop-advpro \
            --git github.com/${{ github.repository }} \
            --git-branch main \
            --ports 8080:http \
            --routes /:8080 \
            --env PORT=8080 \
            --instance-type nano