name: Deploy to Koyeb

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Latest Koyeb CLI
        run: |
          wget -qO koyeb.tar.gz https://github.com/koyeb/koyeb-cli/releases/download/v5.4.0/koyeb-cli_5.4.0_linux_amd64.tar.gz
          tar xvf koyeb.tar.gz
          sudo mv koyeb /usr/local/bin/
          
      - name: Configure Koyeb
        run: |
          echo "token: ${{ secrets.KOYEB_TOKEN }}" > ~/.koyeb.yaml
          
      - name: Deploy to Koyeb
        run: |
          # Skip app creation if it exists
          koyeb service update eshop-advpro \
            --app eshop-advpro-app \
            --git github.com/${{ github.repository }} \
            --git-branch main \
            --ports 8080:http \
            --routes /:8080 \
            --env PORT=8080 \
            --region fra \
            --type web \
            --token ${{ secrets.KOYEB_TOKEN }} || \
          koyeb service create eshop-advpro \
            --app eshop-advpro-app \
            --git github.com/${{ github.repository }} \
            --git-branch main \
            --ports 8080:http \
            --routes /:8080 \
            --env PORT=8080 \
            --region fra \
            --type web \
            --token ${{ secrets.KOYEB_TOKEN }}